### ISSUE TITLE
Fix path to executables under brew

### ISSUE THREAD

**Issue by peaceiris** [peaceiris/actions-self-hosted-runners#2]
## workaround

```yaml
      - name: hadolint
        run: |
          eval $(/home/linuxbrew/.linuxbrew/bin/brew shellenv)
          hadolint ./Dockerfile
```

## expected

```yaml
      - name: hadolint
        run: hadolint ./Dockerfile
```
